# Generated by Django 3.2.5 on 2021-07-09 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool_app', '0002_auto_20210709_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='tool',
            name='id_stage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tool_app.stage'),
        ),
    ]
