# Generated by Django 3.2.5 on 2021-07-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool_app', '0003_auto_20210709_1705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tool',
            old_name='id_stage',
            new_name='stage',
        ),
    ]
